[Eth]
NetworkId = 10
SyncMode = "full"

[Node]
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPModules = ["admin", "eth", "debug", "miner", "net", "txpool", "web3"]
AuthAddr = "0.0.0.0"
AuthPort = 8551
WSHost = "0.0.0.0"
WSPort = 8546
WSOrigins = ["*"]
WSModules = ["admin", "eth", "debug", "miner", "net", "txpool", "web3"]

[Node.P2P]
ListenAddr = ":30303"
DiscAddr = ":30303"
